### ISSUE TITLE
semi-auto derivation for scala 3

### ISSUE THREAD

**Issue by mbore** [softwaremill/magnolia#300]
Currently magnolia 2.0 exposes the given method `Derivation#derived`, which makes auto-derivation the default behaviour for any type class. In some cases it may be undesirable.

Expected behaviour for the `GenericPrint`
```Scala
    case class StrWrapper(str: String)

    test("missing instance") {
      assertDoesNotCompile("""
        summon[Print[StrWrapper]].print(StrWrapper("aaa"))
      """)
    }

    test("derived instance") {
      implicit val printer: Print[StrWrapper] = Print.derived[StrWrapper]
      summon[Print[StrWrapper]].print(StrWrapper("aaa")) shouldBe "StrWrapper(aaa)"
    }
```

**Comment by adamw** [comment]
To add some more context: in my view the role of Magnolia is to automatically generate a method to create an instance of a typeclass. This method by convention is called `Typeclass.derived[T]`. Hence, Magnolia's main role is to create an implementation for this method.

However, currently the `Derivation` trait defines a `given derived[T]: Typeclass[T]`. If the companion object of the typeclass extends this trait, it causes auto-derivation to be enabled for all types, where a higher-priority given isn't defined by the user.

I think this should be changed, so that derived is an ordinary method: `def derived[T]: Typeclass[T]`. Then, the users can decide if they want to have auto-derivation (by defining a given which calls magnolia's derived), or semi-auto, or if they'd like to use the `derives` clause.

One implication of this changes relates to coproducts. Currently, changing the derived from `given` to `def` will cause coproduct tests to fail (see some attempts to fix this in #299). However, I think that instead we should change the logic of derived, so that when called on an enum/sealed trait, it performs the auto-derivation by looking up the children (in the macro), trying to summon existing typeclass instances using `Expr.summon` and if these are not found, creating a default one using the usual mechanism. In other words, the following should work:

```scala
trait MyTypeclass[T]
object MyTypeclass[T] extends Derivation:
 ...

enum Y derives MyTypeclass
  case A
  case B
```

cc @KacperFKorban

**Comment by KacperFKorban** [comment]
I experimented with semi-auto derivation a bit. I'm not quite sure if changing the default behavior to `Expr.summon` will work. Since at the time of generating the typeclass we don't have any givens yet. Also, changing it would most likely mean that the split function will not be called with semi-automatic derivation.(so should it be even defined?) I also managed to make a sealed hierarchy work with a given like this: (Though I am fairly certain that this approach will break for more complicated hierarchies)
```scala
sealed trait Y
case object A extends Y
case class B(s: String) extends Y

import scala.deriving.*
inline given [X <: Y](using Mirror.Of[X]): SemiPrint[X] = SemiPrint.derived[X]
```

**Comment by KacperFKorban** [comment]
Oooo, I think that I know what You meant now. Could You take a look [here](https://github.com/softwaremill/magnolia/tree/semi-auto-derivation)?

**Comment by adamw** [comment]
> Oooo, I think that I know what You meant now. Could You take a look here?

Yes, looks like exactly what we need :) I think in the non-sealed-trait case:

```
val typeclass = CallByNeed(summonOption[Typeclass[p]].get) //<-- not sure about this part
```

we should stay with `summonInline`, which in case of a missing given will result in a normal implicit not found message, instead of an exception from `None.get` :)

Maybe a test that `given[SemiPrint[A]]` fails to compile (that would test, that the we indeed have semi-auto derivation, not auto-derivation)

**Comment by mbore** [comment]
@KacperFKorban  it looks really nice, nevertheless it doesn't work outside of the companion object for recursive structures.
e.g.
```
    test("construct a semi print for a recursive structure") {
      val res = SemiPrint.derived[Recursive]
    }
```
Do you have any ideas on how to work around this?

**Comment by mbore** [comment]
@KacperFKorban it looks really nice, but unfortunately it doesn't work outside of the companion object for recursive structures.
e.g.:
```Scala
    test("construct a semi print for a recursive structure") {
      val res = SemiPrint.derived[Recursive]
    }
```

Do you have any idea how to work around it?

**Comment by mbore** [comment]
@KacperFKorban I will try to implement some way of caching type class instances in tapir, will let you know if I manage to do it.

**Comment by KacperFKorban** [comment]
@mbore @adamw That was one of the problems with parameters and that is why I added the comment. I tried different approaches, but in every case something wasn't working. IMHO having the same logic as with subtypes felt to be most likely to work, but there were problems with that one as well.

**Comment by mbore** [comment]
@KacperFKorban Unfortunately, I haven't managed to fix it with a simple caching. Our next idea is to generate block of methods, which would return typeclass instances, for every case class parameter (similar solution to the [legacy](https://github.com/softwaremill/magnolia/blob/6295f992a8444457fa50f09eb0d741d30ca2e153/src/core/magnolia/magnolia.scala#L267) one)
e.g.
for 
```Scala
case class X(a: Int, b: Y)
case class Y(c: String)
val instance = Show.derived[X]
```
we want to generate 
```Scala
val instance = {
  def xInst = showImpl(intInst, yInst)
  def intInst = showImpl()
  def yInst = showImpl(stringInst)
  def stringInst = showImpl() 
  xInst
}
```
I'm going to work on it.

**Comment by adamw** [comment]
@mbore I think this is fixed by https://github.com/softwaremill/magnolia/pull/304 ?

**Comment by mbore** [comment]
Yes, we can close it

**Comment by adamw** [comment]
Great, one down, 39 to go ;-)
